// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Ratio = require("./Ratio.bs.js");

function calculate(first, second, background) {
  var firstRatio = Ratio.calculate(first, background);
  var secondRatio = Ratio.calculate(second, background);
  if (firstRatio > secondRatio) {
    return first;
  } else {
    return second;
  }
}

exports.calculate = calculate;
/* No side effect */
