// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function toSRGB(color) {
  return color / 255.0;
}

function toRGB(color) {
  if (color <= 0.03928) {
    return color / 12.92;
  } else {
    return Math.pow((color + 0.055) / 1.055, 2.4);
  }
}

function relative(rgb) {
  if (rgb.length !== 3) {
    return 0.0;
  }
  var r = rgb[0];
  var g = rgb[1];
  var b = rgb[2];
  return r * 0.2126 + g * 0.7152 + b * 0.0722;
}

function convert(color) {
  return relative(color.map(toSRGB).map(toRGB));
}

exports.toSRGB = toSRGB;
exports.toRGB = toRGB;
exports.relative = relative;
exports.convert = convert;
/* No side effect */
