// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Ratio = require("./Ratio.bs.js");

function calculateFromRatio(ratio) {
  if (ratio >= 7.0) {
    return "AAA";
  } else if (ratio >= 4.5) {
    return "AA";
  } else if (ratio >= 3.0) {
    return "AA Large";
  } else {
    return "Fail";
  }
}

function calculate(foreground, background) {
  return calculateFromRatio(Ratio.calculate(foreground, background));
}

exports.calculateFromRatio = calculateFromRatio;
exports.calculate = calculate;
/* No side effect */
