// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Best = require("./Best.bs.js");
var Ratio = require("./Ratio.bs.js");
var Score = require("./Score.bs.js");

var ratio = Ratio.calculate;

var score = Score.calculate;

var scoreFromRatio = Score.calculateFromRatio;

var best = Best.calculate;

exports.ratio = ratio;
exports.score = score;
exports.scoreFromRatio = scoreFromRatio;
exports.best = best;
/* No side effect */
