// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/lib/js/src/jest.bs.js");
var Ratio = require("../src/Ratio.bs.js");

Jest.testAll("color contrasts", {
      hd: [
        "#ffffff",
        "#ffffff",
        1.0
      ],
      tl: {
        hd: [
          "ffffff",
          "ffffff",
          1.0
        ],
        tl: {
          hd: [
            "rgb(255, 255, 255)",
            "rgb(255, 255, 255)",
            1.0
          ],
          tl: {
            hd: [
              "rgb(255,255,255)",
              "rgb(255, 255, 255)",
              1.0
            ],
            tl: {
              hd: [
                "hsl(255, 30%, 40%)",
                "hsl(255, 30%, 40%)",
                1.0
              ],
              tl: {
                hd: [
                  "hsl(255,30,40)",
                  "hsl(255, 30%, 40%)",
                  1.0
                ],
                tl: {
                  hd: [
                    "#ffffff",
                    "rgb(255, 255, 255)",
                    1.0
                  ],
                  tl: {
                    hd: [
                      "#ffffff",
                      "#000000",
                      21.0
                    ],
                    tl: {
                      hd: [
                        "#ffffff",
                        "#777777",
                        4.48
                      ],
                      tl: {
                        hd: [
                          "#0088FF",
                          "#C611AB",
                          1.47
                        ],
                        tl: {
                          hd: [
                            "ffffff",
                            "777777",
                            4.48
                          ],
                          tl: {
                            hd: [
                              "fff",
                              "777",
                              4.48
                            ],
                            tl: {
                              hd: [
                                "08f",
                                "fff",
                                3.52
                              ],
                              tl: {
                                hd: [
                                  "rgb(255,255,255)",
                                  "#777777",
                                  4.48
                                ],
                                tl: {
                                  hd: [
                                    "rgb(255,255,255)",
                                    "rgb(77,77,77)",
                                    8.45
                                  ],
                                  tl: {
                                    hd: [
                                      "hsl(0, 0%, 20%)",
                                      "#ffffff",
                                      12.63
                                    ],
                                    tl: {
                                      hd: [
                                        "hsl(210, 30%, 48%)",
                                        "#ffffff",
                                        4.47
                                      ],
                                      tl: {
                                        hd: [
                                          "hsl(210, 30%, 68%)",
                                          "#ffffff",
                                          2.31
                                        ],
                                        tl: {
                                          hd: [
                                            "hsl(0, 0%, 20%)",
                                            "hsl(0, 0%, 100%)",
                                            12.63
                                          ],
                                          tl: {
                                            hd: [
                                              "hsl(0, 100%, 40%)",
                                              "#fff",
                                              5.89
                                            ],
                                            tl: {
                                              hd: [
                                                "hsl(360, 100%, 40%)",
                                                "#fff",
                                                5.89
                                              ],
                                              tl: /* [] */0
                                            }
                                          }
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }, (function (param) {
        return Jest.Expect.toEqual(param[2], Jest.Expect.expect(Ratio.calculate(param[0], param[1])));
      }));

/*  Not a pure module */
