// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/lib/js/src/jest.bs.js");
var Score = require("../src/Score.bs.js");

Jest.testAll("#calculateFromRatio", {
      hd: [
        7.1,
        "AAA"
      ],
      tl: {
        hd: [
          4.6,
          "AA"
        ],
        tl: {
          hd: [
            3.9,
            "AA Large"
          ],
          tl: {
            hd: [
              2.9,
              "Fail"
            ],
            tl: /* [] */0
          }
        }
      }
    }, (function (param) {
        return Jest.Expect.toEqual(param[1], Jest.Expect.expect(Score.calculateFromRatio(param[0])));
      }));

Jest.testAll("#calculate", {
      hd: [
        "#ffffff",
        "#000000",
        "AAA"
      ],
      tl: {
        hd: [
          "#ffffff",
          "#666666",
          "AA"
        ],
        tl: {
          hd: [
            "#ffffff",
            "#888888",
            "AA Large"
          ],
          tl: {
            hd: [
              "#ffffff",
              "#cccccc",
              "Fail"
            ],
            tl: /* [] */0
          }
        }
      }
    }, (function (param) {
        return Jest.Expect.toEqual(param[2], Jest.Expect.expect(Score.calculate(param[0], param[1])));
      }));

/*  Not a pure module */
