name: Run tests on PR

on:
  pull_request:
    branches: 
      - main

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download dependencies
        uses: bahmutov/npm-install@v1

      - name: Build project
        run: npm run build

      - name: Run tests and linting
        run: npm test

